import React from 'react'
import './css/style.css'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-BR">
      <head>
          <meta charSet="UTF-8" />
          <meta name="viewport" content="width=device-width, initial-scale=1.0" />
          <link rel="icon" type="image/png" href="./img/insta-fav.ico" />
          <title>Instagram</title>
      </head>
      <body>
          {children}
      </body>
    </html>
  )
}
